Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-11, with the labels that each got.

#1934 #4343: add message in all languages if user doesn't have data
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1930 #4594 Fixed clearing of the uploaded image when the user goes to another page
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
Labels: bug, UI, GreenCity

#1926 Bugfix/#4590 my events get event of user
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts
Labels: bug, Sev: major

#1938 fixed text style in ubs courier in mobile screen
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.html
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI

#1919 Bugfix/#4489 save changes in user profile
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1935 feature/#4427/Edit tariffs
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/services/create-edit-tariffs-service-form-builder.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, enhancement, UI

#1936 Bugfix/#4566 ubs courier fix next button place in mobile app
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI

#1912 [WIP] Bugfix#4129 save filters on admin table
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/services/admin-table.service.spec.ts
  src/app/ubs/ubs-admin/services/admin-table.service.ts
Labels: bug, UI

#1940 bugfix/#4560 ubs personal cabinet footer in mobile screen
  src/app/shared/ubs-base-sidebar/ubs-base-sidebar.component.scss
  src/app/ubs/ubs-user/ubs-user.component.scss
Labels: bug, UI

#1941 Bugfix/#4692 my space my events added img when user haven't events
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#1942 feature/Add_a_service_Сервіс
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: enhancement, UI

#1952 #4664: check inputs in add certificate
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.ts
Labels: bug, UI

#1960 feature/#4426/Delete_a_service
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.html
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, enhancement, UI

#1959 feature/#4430/Edit_a_service
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, enhancement, UI

#1968 feature/#3860/Edit_courier_name
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.ts
Labels: bug, UI

#1969 Bugfix/#4715 add alert message for edit payment
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.html
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.ts
  src/app/ubs/ubs-admin/components/shared/components/edit-payment-confirmation-pop-up/edit-payment-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/edit-payment-confirmation-pop-up/edit-payment-confirmation-pop-up.component.scss
  src/app/ubs/ubs-admin/components/shared/components/edit-payment-confirmation-pop-up/edit-payment-confirmation-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/edit-payment-confirmation-pop-up/edit-payment-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1974 Bugfix/change request order details
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/services/order.service.ts
Labels: bug, UI

#1976 userstory/#2249-shopping-list-test-coverage
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts_
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.spec.ts
Labels: technical, refactoring, UI, GreenCity

#1975 bugfix/Removed extra input/#4381
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.ts
Labels: bug, UI, GreenCity

#1977 Bugfix/#4706 pop up for add the reason for not taken out
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.html
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.scss
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.spec.ts
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/models/not-taken-out-reason.model.ts
  src/app/ubs/ubs-admin/services/order.service.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI
