Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-09, with the labels that each got.

#1808 Bugfix/#4161/the error messages are absent for 'name' and 'surname' fields when user enters invalid data on the 'user data' page
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
Labels: bug, UI, GreenCity

#1812 Bugfix/#4150/The title of the edit address pop-up changed to 'Змінити адресу'
  src/assets/i18n/ubs/ua.json
Labels: bug, UI, GreenCity

#1813 Bugfix/#4373/Order numbers from Eco shop no longer break out of container
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI, GreenCity

#1815 bugfix/#4164/The_error_messages_are_absent_for_'Phone'_field_when_Admin_enters_invalid_values_on_'Information_about_client'_page
  src/app/shared/ubs-input-error/ubs-input-error.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI, GreenCity

#1832 fix text for read-all-news link in eco-news section
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug, UI, GreenCity

#1822 Bug #4172, cursor in ubs-admin order table cell fixed
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
Labels: bug, UI, GreenCity

#1824 Bug 4173 changed styles in ubs admin order table column Order Number
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-readonly/table-cell-readonly.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-readonly/table-cell-readonly.component.scss
Labels: bug, UI, GreenCity

#1826 UBS_user order page changed some styles of the button 'pay'
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.scss
Labels: bug, UI, GreenCity

#1830 add ru translation for my-events label
  src/assets/i18n/ru.json
Labels: bug, UI, GreenCity

#1835 Bugfix/#4475 header nav links not highlighted
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
Labels: bug, UI, GreenCity

#1837 Changed pre-push strategy: added lint and stylelint check
  package.json
Labels: technical

#1828 [User profile friends-list] at home page output only friend's first name
  src/app/main/component/user/components/profile/users-friends/users-friends.component.html
  src/app/main/component/user/user.module.ts
  src/app/main/pipe/first-string-word/first-string-word.pipe.spec.ts
  src/app/main/pipe/first-string-word/first-string-word.pipe.ts
Labels: bug, UI, GreenCity

#1841 Change request #4576 #4572 Text changes
  src/assets/i18n/ua.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/i18n/ubs-user/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: GreenCity

#1842 bugfix/#3849/UBS admin -> Tariffs (Translation bugs)
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI, GreenCity

#1843 Сhanged styles pop-up window
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-delete-pop-up/ubs-profile-delete-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-delete-pop-up/ubs-profile-delete-pop-up.component.scss
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1844 display order id on order-error page #4226
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.html
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI, GreenCity
