Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-05, with the labels that each got.

#1583 Changed items names like in dto
  src/app/ubs/ubs-user/ubs-user-orders-list/models/ICertificate.interface.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
  src/app/ubs/ubs/services/order.service.spec.ts
Labels: bug, technical

#1595 add ngIf with currentLanguage condition on first span (name of service)
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug, GreenCity

#1598 Bug/#4007-ubs-admin-export-details-fix-timepicker-ui (fixed timePicker UI defect)
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.scss
Labels: UI

#1635 BugFix/change-language-greencity
  src/app/main/i18n/language.service.spec.ts
  src/app/main/i18n/language.service.ts
Labels: bug

#1638 Changed logic on order details page
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug

#1639 Order datails page
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
Labels: bug

#1641 Eco news
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.spec.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
Labels: bug

#1643 Changed logic with counting overpayment to the correct format.
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug
