Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-04, with the labels that each got.

#1561 BugFix#3990/BugFix#3993/Code refactoring#3992
  src/app/chat/chat.module.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.html
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.scss
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-several-orders-pop-up/ubs-admin-several-orders-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-several-orders-pop-up/ubs-admin-several-orders-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-several-orders-pop-up/ubs-admin-several-orders-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-time/table-cell-time.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-time/table-cell-time.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-time/table-cell-time.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/services/order.service.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
Labels: bug, refactoring

#1560 Technical/add unit tests/#3985
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table-excel-popup/ubs-admin-table-excel-popup.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
Labels: technical

#1562 Tecnical/#3972/add unit test
  src/app/main/component/admin/admin.component.spec.ts
  src/app/main/component/admin/admin.component.spec.ts_
  src/app/main/component/admin/admin.component.ts
  src/app/main/component/admin/components/admin-nav/admin-nav.component.spec.ts
  src/app/main/component/admin/components/admin-nav/admin-nav.component.spec.ts_
  src/app/main/component/admin/components/admin-nav/admin-nav.component.ts
  src/app/main/component/admin/components/error/error.component.spec.ts
  src/app/main/component/admin/components/feedbacks/dialog-photo/dialog-photo.component.spec.ts
  src/app/main/component/errors/error/error.component.spec.ts
  src/app/main/component/user/components/user-sidebar/user-sidebar.component.spec.ts
  src/app/main/service/comment/comment.service.spec.ts
  src/app/main/service/comment/comment.service.spec.ts_
  src/app/main/service/comment/comment.service.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.spec.ts_
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-delete-pop-up/ubs-profile-delete-pop-up.component.spec.ts
Labels: technical

#1566 Bugfix/two language translation/#3952
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/order.service.spec.ts
  src/app/ubs/ubs-admin/services/order.service.ts
  src/app/ubs/ubs-user/services/user-orders.service.ts
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/models/UserOrder.interface.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.scss
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.ts
  src/app/ubs/ubs/services/order.service.ts
  src/index.html
Labels: bug

#1568 Feature/#3997 Added notifications about changing order data
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.html
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/services/order.service.ts
Labels: enhancement
