Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-12, with the labels that each got.

#1966 Feature#3851/ Deactivate cards from the pricing page "Тарифи"
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.scss
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
Labels: enhancement, UI

#1957 Bugfix/#4242 ubs admin order filter data
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-admin/components/shared/components/column-filters-pop-up/column-filters-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/admin-table.service.spec.ts
  src/app/ubs/ubs-admin/services/admin-table.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1981 Userstory/#2249 new style shopping list add see all button
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: enhancement, UI, GreenCity

#1986 #4707:add validation for cancellation reason input
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.html
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.scss
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.spec.ts
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.spec.ts_
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1996 Bugfix/#4787 header and footer change
  src/app/main/component/home/components/homepage/homepage.component.scss
  src/app/main/component/layout/components/footer/footer.component.html
  src/app/main/component/layout/components/footer/footer.component.scss
  src/app/main/image-pathes/header-icons.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.scss
  src/assets/img/icon/bookmark-default.svg
  src/assets/img/icon/notifications-default.svg
  src/assets/img/path-4_3.png
Labels: bug, UI

#1989 remove language Ru from language array
  src/app/main/service/header/header.service.ts
Labels: bug, UI

#1990 feature/#4770/Implement notification in user profile cabinet
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
Labels: bug, UI

#1992 Bugfix/#4622 admin customers filter style
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.ts
Labels: bug, UI

#1994 #4663: add logic after reloading page
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug, UI

#2000 bugfix/#4174_The_invalid_export_time_can_be_selected_
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.ts
Labels: bug, UI

#2003 Userstory#2251 new style of shopping list when editing habit
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: enhancement, refactoring, UI, GreenCity

#1998 #4710: error message is displayed correctly
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.spec.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
Labels: bug, UI

#2014 Bugfix/#4628 redirect to ubs page if location is not selected
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.ts
Labels: bug, UI

#2009 Bugfix/#4250 homepage buttons start forming a habit
  src/app/main/component/home/components/homepage/homepage.component.spec.ts
  src/app/main/component/home/components/stat-row/stat-row.component.html
  src/app/main/component/home/components/stat-row/stat-row.component.spec.ts
  src/app/main/component/home/components/stat-row/stat-row.component.ts
  src/app/main/component/home/components/stat-rows/stat-rows.component.spec.ts
Labels: bug, UI

#2012 Userstory#2251 Added ability to delete custom item
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.ts
  src/app/main/component/user/models/shoppinglist.model.ts
Labels: enhancement, UI, GreenCity

#2015 bugfix/#4174/The_invalid_export_time_can_be_selected_
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-several-orders-pop-up/ubs-admin-several-orders-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-several-orders-pop-up/ubs-admin-several-orders-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-select/table-cell-select.component.ts
Labels: bug, UI

#2016 Bugfix/#4800 admin can create order
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.html
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.spec.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
Labels: bug, UI

#2017 Bugfix/#4825 ubs admin tariffs add location date translation
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2018 Added translate for labels and placeholders
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2019 bugfix/#4819 UBS admin - Tariffs - Add Location - input autocomplite translation in Ua
  src/index.html
Labels: bug, UI

#2020 bugfix/#4843/UBS-PRICING-PAGE]._404_Error_appears_while_creating_tariffsForServices
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
Labels: bug, UI

#2023 bugfix/#4818 - UBS Admin - Tariffs - Add location pop up - region input suggestion
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2011 #4817: redirect to friend's page
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-requests/request-item/request-item.component.html
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-requests/request-item/request-item.component.scss
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-requests/request-item/request-item.component.spec.ts
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-requests/request-item/request-item.component.ts
Labels: bug, UI, GreenCity

#1963 Bugfix/#4590 My Space - My Events - get created events
  src/app/main/component/events/services/events.service.spec.ts
  src/app/main/component/events/services/events.service.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts
Labels: bug, UI

#2027 bugfix/#4820 UBS Admin > Tariffs > Add location pop up - city input error message
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2028 Bugfix/#4621 add info about certificate
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
Labels: bug, refactoring, UI

#2030 deleted item from sidebar
  src/app/ubs/ubs/models/ubs-sidebar-links.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2031 Bugfix/#4867 ubs admin tariffs add location pop up region inputs en
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/index.html
Labels: bug, UI
