Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-10, with the labels that each got.

#1851 Bugfix/#4324 & #4626 UI inconsistency in edit page user data
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
Labels: bug, UI

#1848 fix edit-data btn styles
  src/app/main/component/home/components/homepage/homepage.component.spec.ts
  src/app/shared/header/header.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
Labels: bug, Sev: minor, UI

#1853 bugfix/#4509 the title is displayed fully eco news
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.scss
Labels: bug, Sev: minor, UI

#1854 Change request/#4575 ubs home page how to prepare block changes
  src/app/main/image-pathes/ubs-main-page-images.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.html
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
  src/assets/img/ubs/black-package-cut.png
Labels: UI

#1859 Add a service "Сервіс" to the tariffs card #4428
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.html
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
Labels: enhancement, UI

#1860 Fixed bug #4604
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
Labels: bug

#1861 Bugfix/#4623 - Added resizing for recommended news cards
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-widget/eco-news-widget.component.html
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-widget/eco-news-widget.component.scss
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.scss
Labels: bug, Sev: minor, UI

#1862 footer changes
  src/app/shared/ubs-footer/ubs-footer.component.html
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#1863 add hover styles on blocks in home pageaccording to tyhe change request
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.html
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/assets/i18n/ubs/ua.json
Labels: UI

#1858 bugfix #4137 UI inconsistency on the Order form Step 3
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#1865 Bugfix/#4477 - share news to LinkedIn
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
Labels: bug, UI, Sev: major

#1870 Bigfix/#4624 - Fixed comments section display on single view news page
  src/app/main/component/comments/components/add-comment/add-comment.component.scss
Labels: bug, UI

#1871 Added missed error message
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
Labels: bug, UI

#1884 bugfix/#4454 - event online link placeholder changed
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.html
Labels: bug, UI, Sev: trivial

#1878 #3906: Changed the warning message in cancel popup
  src/assets/i18n/ubs-admin/en.json
Labels: bug, UI

#1885 Bugfix/#4467 white spaces forbidden in create event
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug, UI

#1877 Order payment impossibility, added notification pop-ups for conditions…
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.spec.ts
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/shared/interceptors/interceptor.service.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#1888 #4587: edit error message upload-photo
  src/app/main/component/events/components/images-container/images-container.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug, UI

#1896 fixed error message style
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
Labels: bug, UI

#1892 Bugfix/4393 edit check oldpass
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#1890 Bugfix#4587 add check photo upload
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
Labels: bug, UI

#1879 Bugfix/#4163 missed error message for Name Surname fields
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug, UI

#1876 Bugfix/#4609 upload image size validation create news
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
Labels: bug, Sev: minor

#1882 #4466: Add error message on Create event page for unauthorized user
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug, UI

#1886 fixed display of payment status
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug, UI

#1899 feature/#4429/Add_a_service_Послуга_to_the_tariffs_card_#4429
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: enhancement, UI

#1866 Bugfix/#4478 eco news date is not translated
  src/app/main/component/home/components/eco-events/eco-events-item/eco-events-item.component.html
  src/app/main/component/home/components/eco-events/eco-events-item/eco-events-item.component.spec.ts
  src/app/main/component/home/components/eco-events/eco-events.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/translate-date-pipe/translate-date.pipe.spec.ts
  src/app/shared/translate-date-pipe/translate-date.pipe.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-date/table-cell-date.component.spec.ts
Labels: bug, Sev: minor, UI, GreenCity

#1901 Fixed tests from pr #1886
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.spec.ts
Labels: bug

#1902 Bugfix/#4459 new style edit button in violation pop up
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.html
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.scss
Labels: bug, UI

#1904 #4601: edit text in tooltip
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug, UI

#1907 feature/#4429/Correct_disable_behaviour_of_buttons_save_changes_and_duplicate
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
Labels: bug, enhancement, UI

#1893 saving habits view type to localStorage
  src/app/main/component/user/components/habit/all-habits/all-habits.component.spec.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.ts
  src/app/main/service/localstorage/local-storage.service.ts
Labels: bug, Sev: minor, UI, GreenCity

#1889 Bugfix/#4638 single view of news open page by link
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.spec.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.spec.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.ts
  src/app/main/component/eco-news/models/create-news-interface.ts
  src/app/main/component/eco-news/services/create-eco-news.service.spec.ts
  src/app/main/component/eco-news/services/create-eco-news.service.ts
  src/app/main/component/eco-news/services/eco-news.service.spec.ts
  src/app/main/component/eco-news/services/eco-news.service.ts
Labels: bug, UI

#1908 Enhancement of saveChanges method
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
Labels: bug, enhancement, UI

#1911 Bugfix/#4541 create news page fix unconformity to mockup
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.scss
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.html
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, Sev: minor

#1914 refactoring of button styles on the order page
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI

#1920 Bugfix/#4330 UI inconsistencies in massages user page
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.html
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.scss
Labels: bug, UI

#1916 Bugfix/#4543 #4544 create news warning messages
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
Labels: bug, Sev: trivial

#1922 bugfix/#4501 eco news tags saved in session storage
  src/app/main/component/eco-news/components/news-list/news-list.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list.component.ts
  src/app/main/component/shared/components/tag-filter/tag-filter.component.spec.ts
  src/app/main/component/shared/components/tag-filter/tag-filter.component.ts
Labels: bug, Sev: major

#1925 #4610: fix position if search icon
  src/app/shared/header/header.component.scss
Labels: bug, UI

#1923 Bugfix/#4513 changed styles on the screen wider then 1440px
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.scss
Labels: bug, UI, GreenCity
