Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-01, with the labels that each got.

#1443 Bugfix/ubs header translate
  src/app/main/main.component.spec.ts
  src/app/main/main.component.ts
  src/app/shared/header/header.component.scss
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.scss
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.scss
  src/app/ubs/ubs/ubs-order.component.html
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug

#1444 Feature/ngrx store
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/shared/interceptors/interceptor.service.ts
  src/app/store/actions/employee.actions.ts
  src/app/store/effects/employee.effects.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/reducers/employee.reducer.ts
  src/app/store/state/app.state.ts
  src/app/store/state/employee.state.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/employee-form/employee-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/employee-form/employee-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-card/ubs-admin-employee-card.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.spec.ts
Labels: enhancement, dependencies

#1446 Bugfix/ubs order autocomplete from localstorage
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
Labels: bug

#1447 Bugfix/incorrect discount after canceling certificates/#3018
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/services/ubs-order-form.service.ts
Labels: bug

#1450 Bugfix/extra empty data from order
  src/app/main/component/auth/components/auth-modal/auth-modal.component.spec.ts
  src/app/main/service/auth/pop-up/pop-up-view.service.spec.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
Labels: bug

#1456 Bugfix/#3754/redirection to confirm page after payment from user page
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/models/IOrderData.interface.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.html
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.spec.ts
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug

#1465 Bugfix/remove button order again and check pay button and fix bonuses/#3489/#3654
  src/app/ubs/ubs-user/ubs-user-bonuses/models/BonusModel.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/models/BonusesModel.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/models/IBonus.interface.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/services/bonuses.service.spec.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/services/bonuses.service.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/ubs-user-bonuses.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-bonuses/ubs-user-bonuses.component.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/models/IBonusInfo.interface.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/models/IOrderData.interface.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.html
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug

#1467 Bugfix/order payment invalid field name/#3742
  package-lock.json
  package.json
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.html
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.scss
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.ts
  src/app/ubs/ubs-admin/components/shared/components/show-imgs-pop-up/show-imgs-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/show-imgs-pop-up/show-imgs-pop-up.component.scss
  src/app/ubs/ubs-admin/components/shared/components/show-imgs-pop-up/show-imgs-pop-up.component.ts
  src/app/ubs/ubs-admin/components/shared/components/show-pdf-pop-up/show-pdf-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/show-pdf-pop-up/show-pdf-pop-up.component.scss
  src/app/ubs/ubs-admin/components/shared/components/show-pdf-pop-up/show-pdf-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/show-pdf-pop-up/show-pdf-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, dependencies

#1468 Bugfix/change from user orders success payment text from accepted to paid/#3650
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.html
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ru.json
  src/assets/i18n/ubs/ua.json
Labels: bug

#1473 Feature/pwa
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/shared/interceptors/interceptor.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ru.json
  src/assets/i18n/ubs/ua.json
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-48x48.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/index.html
  src/manifest.webmanifest
Labels: enhancement, dependencies

#1478 bugFix/#3500/[UBS-user profile]/empty name and surname fields
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
Labels: bug

#1487 Bugfix/translate on page update/#3800
  src/app/app.module.ts
  src/app/main/i18n/language.service.ts
Labels: bug

#1476 bugFix/ubs-user/#3792/incorrect display paid amount in order details
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.html
Labels: bug

#1477 bugFix/ #2615/[Edit Profile] Improvement to error messages on the ‘My habits’ page
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/i18n/ua.json
Labels: bug

#1480 Bugfix/dynamically use bonuses in user payment/#3489
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/assets/i18n/ubs-admin/ua.json
Labels: bug

#1489 Bugfix/fix update order from admin page/#3814
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/order.service.ts
Labels: bug

#1492 Bugfix/set liqpay on submit button/#3823
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug
