Repository ita-social-projects/GreenCityClient, pull requests merged in 2022-06, with the labels that each got.

#1655 Eco news #2
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news-form-builder.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.html
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.spec.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.html
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.ts
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.html
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.ts
  src/app/main/component/eco-news/components/news-list/news-list.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list.component.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.spec.ts
  src/app/main/component/eco-news/models/create-news-interface.ts
  src/app/main/component/eco-news/models/eco-news-model.ts
  src/app/main/component/eco-news/services/eco-news.service.spec.ts
  src/app/main/component/eco-news/services/eco-news.service.ts
  src/app/main/pipe/safe-html-pipe/safe-html.pipe.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
Labels: refactoring

#1657 Restore password email
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.html
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.scss
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.spec.ts
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.ts
  src/app/main/component/auth/components/restore-password/restore-password.component.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.scss
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/model/restroreDto.ts
  src/app/main/service/auth/restore-password.service.spec.ts
  src/app/main/service/auth/restore-password.service.ts
  src/app/main/service/route-guards/confirm-restore-password.guard.spec.ts
  src/app/main/service/route-guards/confirm-restore-password.guard.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/app/ubs/ubs/ubs-routing.module.ts
Labels: enhancement, refactoring

#1659 Added violation images to the User notification images
  src/app/ubs/ubs-admin/models/ubs-user.model.ts
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.html
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.scss
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug

#1654 Feature/#4051/Accordion added to Table-view dropdown
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
Labels: enhancement

#1691 [UBS-User. Orders tab view] "Коментар до замовлення" field is present in the wrong place in form #4311
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.html
Labels: bug

#1713 Fixed styles in the employee table
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
Labels: bug
