Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-07, with the labels that each got.

#2545 bugfix/#5964/CreateNews_ReplacingTheWord
  src/assets/i18n/en.json
Labels: bug

#2555 Bugfix/#5977/error message for more than 50 characters
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: to-do list

#2554 Bugfix/#6002#5948#5947/create news
  src/app/main/component/shared/components/tags-select/tags-select.component.spec.ts
  src/app/main/component/shared/components/tags-select/tags-select.component.ts
Labels: bug, GreenCity

#2556 bugfix/#6008/An extra inscription was mistakenly present in the pop up window
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-station-pop-up/ubs-admin-tariffs-station-pop-up.component.html
Labels: UI

#2562 bugfix/Add-logic-for-filters-on-the-employee-page
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.ts
  src/app/store/actions/employee.actions.ts
  src/app/store/effects/employee.effects.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.spec.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, refactoring, UI

#2569 Bugfix/#5818 add rate ability at more about event page
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
Labels: bug, UI

#2577 bugfix/#5803-Imlementation-of-endpoint
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs-admin/services/order.service.ts
  src/app/ubs/ubs-admin/services/orderInfoMock.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug

#2579 Feature/get districts from back end
  src/app/main/service/location/location.service.ts
  src/app/main/service/location/location.spec.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.html
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.spec.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.ts
  src/app/ubs/mocks/address-mock.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/orderInfoMock.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.spec.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
  src/app/ubs/ubs/services/order.service.spec.ts
  src/app/ubs/ubs/services/order.service.ts
  src/assets/locations/locations.spec.ts
Labels: enhancement, UI

#2586 Bugfix/#6045-Fix bug of adding habits
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.spec.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.ts
  src/app/main/service/habit-assign/habit-assign.service.ts
Labels: bug, UI

#2590 bugfix/prod-Add-translation-of-error-message-at-order-cretificate-section
  src/assets/i18n/ubs/en.json
Labels: bug, UI

#2592 bugfix/#6074,#6075,#6076,#6077,#6078-Changing-the-access-to-elements-of-admin-sidemenu-according-to-employees-roles
  src/app/main/component/auth/components/sign-in/sign-in.component.spec.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.ts
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/shared/ubs-base-sidebar/ubs-base-sidebar.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-sidebar/ubs-admin-sidebar.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-sidebar/ubs-admin-sidebar.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.ts
  src/app/ubs/ubs-user/ubs-user-sidebar/ubs-user-sidebar.component.ts
Labels: bug, UI
