Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-02, with the labels that each got.

#2114 feature/#5107/The visualization of the Event preview card and display of its elements is not matched with their design
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/image-pathes/auth-images.ts
  src/app/main/image-pathes/sign-in-icons.ts
  src/assets/events-icons/author.png
  src/assets/events-icons/date.png
  src/assets/events-icons/frame.png
  src/assets/events-icons/like.png
  src/assets/events-icons/lock-closed.png
  src/assets/events-icons/lock-open.png
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: UI, GreenCity

#2115 Bugfix/#5019 change error message for number pattern error
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2118 Bugfix/#5084 tariffs create card labels and date translation
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2119 bugfix/#5165/Tariffs for services are not displayed
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, UI

#2121 Bugfix/#5127 elements are not properly aligned
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2122 Bugfix/#5059 column exported amount should has value according to status
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug, UI

#2125 New design for UBS main page
  src/app/main/image-pathes/header-icons.ts
  src/app/main/image-pathes/ubs-main-page-images.ts
  src/app/main/service/header/header.service.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.scss
  src/app/shared/header/header.component.ts
  src/app/shared/ubs-footer/ubs-footer.component.html
  src/app/shared/ubs-footer/ubs-footer.component.scss
  src/app/shared/ubs-footer/ubs-footer.component.ts
  src/app/ubs/ubs-user/ubs-user.component.scss
  src/app/ubs/ubs/components/ubs-main-page-spinner/ubs-main-page-spinner.component.html
  src/app/ubs/ubs/components/ubs-main-page-spinner/ubs-main-page-spinner.component.scss
  src/app/ubs/ubs/components/ubs-main-page-spinner/ubs-main-page-spinner.component.spec.ts
  src/app/ubs/ubs/components/ubs-main-page-spinner/ubs-main-page-spinner.component.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.html
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/app/ubs/ubs/ubs-order.module.ts
  src/assets/admin-header/face-icon.svg
  src/assets/admin-header/insta-icon.svg
  src/assets/admin-header/logo-footer.svg
  src/assets/admin-header/new-logo-admin.svg
  src/assets/admin-header/telegram-icon.svg
  src/assets/admin-header/you-tube-icon.svg
  src/assets/i18n/ubs-admin/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
  src/assets/img/filled_arrow_down.svg
  src/assets/img/ubs/auto.svg
  src/assets/img/ubs/bag.svg
  src/assets/img/ubs/ubs_pick_up.png
  src/assets/img/ubs/ubs_pick_up.svg
  src/typography/_colorsUbs.scss
Labels: UI

#2124 bugfix/#5193/[Pricing Page] Limits are not displayed
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
Labels: bug, UI

#2134 bugfix/#5205/Order]Min/max_validator_is_missing._Also_min/max_error_message_is_absent_too
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
Labels: bug, UI

#2133 bugfix/#4999/The_input_of_the_field_УБС-кур'єр'_does_not_have_value_'50_грн'_by_default_and_is_disabled
  src/app/shared/localized-date-pipe/localized-date.pipe.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
Labels: bug, UI

#2129 bugfix/#5075/Admin_can_set_past_time_of_the_current_date_for_the_order_and_save_this_changes
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
Labels: bug, UI

#2136 added on preview event lock closed icon
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/assets/img/events/lock-closed.svg
Labels: bug, UI

#2145 bugfix/#5221/Change_scrollBar_styles
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
Labels: bug, UI

#2101 Code optimization check language
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news-form-builder.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.spec.ts
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list-gallery-view/news-list-gallery-view.component.ts
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list-list-view/news-list-list-view.component.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.html
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.spec.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/i18n/language.service.spec.ts
  src/app/main/i18n/language.service.ts
  src/app/main/interface/langValue.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.html
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.ts
  src/app/store/reducers/tariff.reducer.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-station-pop-up/ubs-admin-tariffs-station-pop-up.component.ts
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.html
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/address/address.component.html
  src/app/ubs/ubs/components/ubs-personal-information/address/address.component.spec.ts
  src/app/ubs/ubs/components/ubs-personal-information/address/address.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.spec.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: UI

#2149 added style changes for sign in and sign up
  src/app/main/component/auth/components/auth-modal/auth-modal.component.scss
  src/app/main/component/auth/components/sign-in/sign-in.component.scss
  src/app/main/component/auth/components/sign-up/sign-up.component.scss
Labels: bug, UI

#2140 Bugfix/#5207 add event details ua translation
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2148 bugfix/#5241/[App] Unification of scroll bar styles all over the page
  src/app/chat/component/chat/chat.component.scss
  src/app/chat/component/chats-list/chats-list.component.scss
  src/app/chat/component/new-message-window/new-message-window.component.scss
  src/app/main/component/events/components/event-details/event-schedule/event-schedule.component.scss
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.scss
  src/app/ubs/ubs-admin/components/shared/components/column-filters-pop-up/column-filters-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification-edit-form/ubs-admin-notification-edit-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification-settings/ubs-admin-notification-settings.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
  src/styles.scss
Labels: bug, UI

#2152 Bugfix/#4499 my habits preview card fix
  src/app/main/component/user/components/profile/calendar/habits-popup/habits-popup.component.spec.ts
  src/app/main/component/user/components/profile/calendar/habits-popup/habits-popup.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts
  src/app/main/component/user/services/format-date.service.spec.ts
  src/app/main/component/user/services/format-date.service.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-station-pop-up/ubs-admin-tariffs-station-pop-up.component.ts
Labels: bug, UI

#2151 bugfix/#5245/[UBS. Admin. Tariffs] The 404 occurs when Admin adds new service into the tariffs card
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, UI

#2153 bugfix/#5250 - registration dialog - added trim method for inputs values
  src/app/main/component/auth/components/sign-up/sign-up.component.html
  src/app/main/component/auth/components/sign-up/sign-up.component.spec.ts
  src/app/main/component/auth/components/sign-up/sign-up.component.ts
Labels: bug, UI

#2154 bugfix/#2542 - added day or days in a row message for habits
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.html
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-news/one-news.component.spec.ts_
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2156 bugfix/#5156-Change pattern for adding certificate
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.ts
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2157 Feature/#5212 pop up for about service page
  src/app/main/service/header/header.service.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.scss
  src/app/shared/header/header.component.ts
  src/app/shared/ubs-footer/ubs-footer.component.scss
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.scss
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.html
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.scss
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.spec.ts
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.ts
  src/app/ubs/ubs/ubs-order.module.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
  src/assets/img/ubs/arrow_right_ubs_popup_list.svg
Labels: UI

#2160 Added changes of styles and texts at pop-ups
  src/app/main/component/auth/components/sign-up/sign-up.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/assets/i18n/ubs-admin/en.json
Labels: bug, UI

#2164 Bugfix/#5277 all habits page img and tags display
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.html
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.scss
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.html
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.scss
  src/assets/img/habits/man.svg
Labels: bug, UI

#2173 Bugfix/#5306 add edit habit page change invite friends style
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-invite-friends/habit-invite-friends.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-invite-friends/habit-invite-friends.component.scss
  src/assets/icons/habits/plus-circle-grey.svg
Labels: bug, UI

#2178 bugfix/#5315 - add/edit habit page - added image on error
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
Labels: bug, UI

#2166 Tasks No 5251 and 5242
  src/assets/i18n/en.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: UI

#2169 enchancement for pick-up-pop-up
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/pick-up-text.ts
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.scss
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: enhancement, UI

#2170 feature/#5304/[Events]New header for Events
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/events.module.ts
  src/app/main/component/events/models/event-consts.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/image-pathes/auth-images.ts
  src/assets/events-icons/bookmark-active.png
  src/assets/events-icons/bookmark-grey.png
  src/assets/events-icons/bookmark-set.png
  src/assets/events-icons/cross.png
  src/assets/events-icons/my-event.png
  src/assets/events-icons/search-active.png
  src/assets/events-icons/search-hover.png
  src/assets/events-icons/search.png
Labels: UI, GreenCity

#2171 Bugfix/#4842 - add edit habit page - mark as done
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
  src/assets/icons/habits/plus-circle-green.svg
Labels: bug, UI

#2176 bugfix/#5307 - My habits - add cursor pointer on pencil and change color on hover
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.scss
Labels: bug, UI

#2177 bugfix/#5314 my habits - display acquired habits even if user haven't habits in progress
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
Labels: bug, UI

#2179 bugfix/#5276/[Green city. Events] The buttons 'Cancel'/'Preview'/ 'Publish' are not aligned according to mock up on the page 'Create event'
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
Labels: bug, UI, GreenCity

#2180 bugfix/#5162 Added default Date section on Create event page
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
Labels: bug, UI

#2186 bug Spelling mistake #5158
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
Labels: bug, UI, GreenCity

#2187 bugfix/#5156: changed pattern, field accept only integer
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2183 Bugfix/#5323 my habits fixed day counter
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts
Labels: bug, UI

#2181 Bugfix/#5295 create event and join to event bttn not displayed for the non auth user
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/events.module.ts
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
Labels: bug, UI

#2168 bugfix/#5238,#5239,#5240,#5248,#5273 Added changes to form validators
  src/app/main/component/auth/components/error/error.component.spec.ts
  src/app/main/component/auth/components/error/error.component.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.ts
  src/app/main/component/auth/components/sign-up/sign-up.validator.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.scss
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI, GreenCity

#2175 feature/#5311/checkBoxes,changed endpoints
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, enhancement, UI
