Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-03, with the labels that each got.

#2185 Bugfix/enhancement for bags displaying
  src/app/main/service/localstorage/local-storage.service.spec.ts
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.spec.ts
  src/app/ubs/ubs/services/order.service.spec.ts
  src/app/ubs/ubs/services/order.service.ts
Labels: enhancement

#2165 Secondary labels and placeholders are missing translation
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2191 #5331: changed text at create order pop-up
  src/assets/i18n/ubs/en.json
Labels: bug, UI

#2161 bugfix/#4833 add form to confirm deleting habit
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.html
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.scss
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2189 Bugfix/#4561 displaying order table for mobile
  src/app/shared/ubs-footer/ubs-footer.component.html
  src/app/shared/ubs-footer/ubs-footer.component.scss
  src/app/shared/ubs-footer/ubs-footer.component.spec.ts
  src/app/shared/ubs-footer/ubs-footer.component.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.scss
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.html
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.scss
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.ts
  src/app/ubs/ubs-user/ubs-user.component.scss
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.html
  src/app/ubs/ubs/components/ubs-pick-up-service-pop-up/ubs-pick-up-service-pop-up.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/img/icon/info-icon.svg
Labels: enhancement, UI

#2197 #5356: fix payment with expired and used certificates
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
Labels: bug

#2199 Bugfix/#5361 add the infinite scroll on the event dashboard
  src/app/main/component/eco-news/components/news-list/news-list.component.ts
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/store/actions/ecoEvents.actions.ts
  src/app/store/effects/ecoEvents.effects.ts
  src/app/store/reducers/ecoEvents.reducer.ts
Labels: bug, UI

#2200 feature/#/switching tariff status
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: enhancement, UI

#2205 Bugfix/#5073
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI

#2208 Bugfix/fixing addresses in user profile
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/i18n/ubs-user/en.json
  src/assets/i18n/ubs-user/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
  src/assets/img/icon/trash-bin.svg
Labels: UI

#2209 Bugfix/#5373 improvement for order details
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-responsible-persons/ubs-admin-responsible-persons.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, enhancement, UI

#2211 Bugfix/#5387 remove extra columns in order list
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2207 Bugfix/#5308 edit habit add acquire button
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habits-widget/habits-widget.component.ts
  src/app/main/service/habit-assign/habit-assign.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2206 Bugfix/#5358,#5362,#5367-translate-into-UA-filters-sorting-elements,results-of-sorting,style-chechboxes
  src/app/main/component/eco-news/components/news-list/news-list.component.ts
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/models/event-consts.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2223 Bugfix/#5279 counting ubs courier with sum of order
  src/app/store/actions/orderStatus.actions.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/reducers/orderStatus.reducer.ts
  src/app/store/state/app.state.ts
  src/app/store/state/orderStatus.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: technical

#2212 bugfix/#5383,#5384-Change-label-name-and-last-name-in-Edit-employee-data-window
  src/assets/i18n/ubs-admin/en.json
Labels: bug, UI

#2213 bugfix/#5401 - added snackbar notification - after reject give up habit
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.spec.ts
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2217 Bugfix/#4040 [Eco-News] BugFix_Incorrect_routing #4040
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.html
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.spec.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts
Labels: bug

#2220 [UBS_Prod. Client. Order. Step 1 'Order details'] The scroll and the ability to extend the field 'Коментар' are available for the User in Step 1 'Order details' #5330
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
Labels: bug

#2221 Bugfix/#5399/#5408 - amont users that acquired habits and calendar icon fix
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.scss
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habits-widget/habits-widget.component.spec.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.spec.ts
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.html
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.scss
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.html
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.html
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.scss
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.spec.ts
  src/app/main/component/user/models/HabitMark.enum.ts
  src/app/main/interface/habit/habit-assign.interface.ts
  src/app/main/interface/habit/habit.interface.ts
  src/app/main/mocks/habit-assign-mock.ts
  src/app/main/service/habit/habit.service.spec.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/icons/habits/calendar-green.svg
Labels: bug, UI

#2224 Bugfix/fixed footer positioning in order
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.scss
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.scss
Labels: UI

#2230 bugfix/#5284-Disable 'Save' btn in the raite modal in case if rating is not selected
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.ts
Labels: bug, UI

#2233 [UBS_Prod. Client. Order. Step 1 'Order details'] The 'Додати ще сертифікат' bttn is not displayed after the User adds services additionally to the order #5332
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
Labels: bug

#2210 code optimization - added global buttons
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.scss
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/main/component/eco-news/components/news-list/news-list.component.html
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.html
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.scss
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.scss
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/home/components/homepage/homepage.component.html
  src/app/main/component/home/components/homepage/homepage.component.scss
  src/app/main/component/home/components/stat-row/stat-row.component.html
  src/app/main/component/home/components/stat-row/stat-row.component.scss
  src/app/main/component/home/components/subscribe/subscribe.component.html
  src/app/main/component/home/components/subscribe/subscribe.component.scss
  src/app/main/component/places/components/add-place/add-place.component.html
  src/app/main/component/places/components/add-place/add-place.component.scss
  src/app/main/component/places/places.component.html
  src/app/main/component/places/places.component.scss
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.html
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.scss
  src/app/main/component/shared/components/edit-photo-pop-up/edit-photo-pop-up.component.html
  src/app/main/component/shared/components/edit-photo-pop-up/edit-photo-pop-up.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up-ubs.component.scss
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.html
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.scss
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.html
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.scss
  src/app/main/component/user/components/profile/edit-profile/edit-profile.component.html
  src/app/main/component/user/components/profile/edit-profile/edit-profile.component.scss
  src/app/main/component/user/components/profile/edit-profile/personal-photo/personal-photo.component.html
  src/app/main/component/user/components/profile/edit-profile/personal-photo/personal-photo.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.scss
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-item/friend-item.component.html
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-item/friend-item.component.scss
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.html
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.scss
  src/app/shared/header/header.component.html
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.html
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.scss
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.spec.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/styles.scss
  src/typography/_typography.scss
Labels: UI

#2228 Feature/#5423 switcher for social media
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-switcher/ubs-switcher.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-switcher/ubs-switcher.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-switcher/ubs-switcher.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-switcher/ubs-switcher.component.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/app/ubs/ubs-user/ubs-user.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: enhancement, UI

#2235 bugfix - ubs order - second step validation
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
Labels: bug, UI

#2234 bugfix/#5437/UBS_Admin.Orders.Order_Details
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.html
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.scss
Labels: bug

#2237 Bugfix/#5462 All habits - incorrect working of filtering
  src/app/main/component/user/components/habit/all-habits/all-habits.component.html
  src/app/main/component/user/components/habit/all-habits/all-habits.component.spec.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.ts
  src/app/main/service/habit/habit.service.spec.ts
  src/app/main/service/habit/habit.service.ts
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-profile-change-password-pop-up/ubs-profile-change-password-pop-up.component.spec.ts
Labels: bug, UI

#2238 bugfix/#5473 - UBS admin - employees permission dialog - add scroll and close dialog
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
Labels: bug, UI

#2239 bugfix/#5229 - ubs addresses - autofill of districts - wrong districts
  src/app/shared/to-first-capital-letter/to-first-capital-letter.service.spec.ts
  src/app/shared/to-first-capital-letter/to-first-capital-letter.service.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.spec.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.ts
Labels: bug, UI

#2240 feature/#5478/[Pricing Page]Implement possibility to edit tariff
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: enhancement

#2245 bugfix/#5457,#4884-Add translation, validation, styles in the "Add certificates admin pop-up"
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2246 #5366/bugfix-remove-buttons-from-acquired-habits
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/interface/habit/habit-assign.interface.ts
  src/app/main/interface/habit/habit.interface.ts
Labels: bug, UI

#2222 bugfix/#5288,#5329,#5161-Translation-into-UA-styles-handling-rating-modal-window, fix infinity scroll
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/store/reducers/ecoEvents.reducer.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2252 Bugfix/#5232/#5233 sign up user name and email error messages
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2251 bugfix/5438,#5463-Add modal window if reason is "Not taken out" in admin order history
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.html
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.scss
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.ts
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.html
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.ts
  src/app/ubs/ubs-admin/models/not-taken-out-reason.model.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/order.service.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2254 #5505 added text on hover for admin order columns
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-readonly/table-cell-readonly.comoponent.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-readonly/table-cell-readonly.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-readonly/table-cell-readonly.component.ts
Labels: UI

#2256 Bugfix/#5037/my habits.edit profile
  src/app/main/component/user/components/profile/edit-profile/personal-photo/personal-photo.component.html
  src/app/main/component/user/components/profile/edit-profile/personal-photo/personal-photo.component.scss
  src/app/main/component/user/components/shared/components/user-profile-image/user-profile-image.component.scss
Labels: bug

#2257 Bugfix/#5488 my habits sort from last added habit
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts
Labels: bug, UI

#2261 bugfix/#5425/UBS_Admin.Orders.Order_details
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
Labels: bug

#2270 bugfix/#5514-Add error message if certificate not-exist in DB
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2266 bugfix/#4884-Added-styles-in-the-add-certificate-popup-according-new-mock-up
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2262 Bugfix/#5432 changes for export details form for status done
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/services/orderInfoMock.ts
Labels: UI

#2274 bugfix/#4884-Add-changes-in-the-add-certificate-popup-according-to-new-mock-up
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2241 bugfix/#5178_#5474/UBS_Admin.Orders.Order_Details
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.html
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.scss
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/patterns/patterns.ts
Labels: bug

#2286 bugfix/#5514-Added-error-message-if-certificate-not-exist-in-DB
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs/ua.json
Labels: UI

#2253 Bugfix/#5506 - All Habits - assign again to acquired habits
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/shopping-list.service.ts
  src/app/main/component/user/components/habit/add-new-habit/habits-widget/habits-widget.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habits-widget/habits-widget.component.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.ts
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts
  src/app/main/component/user/components/profile/shopping-list/shopping-list.component.spec.ts
  src/app/main/component/user/components/profile/shopping-list/shopping-list.component.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.spec.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.ts
  src/app/main/component/user/models/shoppinglist.model.ts
  src/app/main/component/user/user-routing.module.ts
  src/app/main/interface/habit/habit.interface.ts
  src/app/main/service/habit-assign/habit-assign.service.spec.ts
  src/app/main/service/habit-assign/habit-assign.service.ts
  src/app/main/service/habit/habit.service.spec.ts
  src/app/main/service/habit/habit.service.ts
Labels: bug, UI

#2287 Remove-border-on-Sign-In-button
  src/app/shared/header/header.component.scss
Labels: UI

#2290 bugfix/change-form-validators
  src/app/main/component/auth/components/error/error.component.spec.ts
  src/app/main/component/auth/components/error/error.component.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.ts
  src/app/main/component/auth/components/sign-up/sign-up.validator.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.scss
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: UI
