Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-11, with the labels that each got.

#2751 The size of GreenCity Footer for Display Resolution Sizes 320px don't match the mock-up
  src/app/main/component/layout/components/footer/footer.component.scss
Labels: GreenCity

#2770 bugfix/#6638 Add ability to see message about bonuses return in order details
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs/order-status.enum.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2759 Bugfix/#6554#6556#6557#6506#6558#6553/If user chooses a habit with a very long name, button 'Edit' in 'My Space' page disappears
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.html
  src/app/main/component/user/components/habit/all-habits/all-habits.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.scss
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.scss
Labels: bug, My Habits

#2779 fix employee page loading
  src/app/main/main.component.spec.ts
  src/app/shared/header/header.component.spec.ts
  src/app/shared/header/header.component.ts
  src/app/shared/ubs-base-sidebar/ubs-base-sidebar.component.spec.ts
  src/app/shared/ubs-base-sidebar/ubs-base-sidebar.component.ts
  src/app/store/reducers/employee.reducer.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-sidebar/ubs-admin-sidebar.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-sidebar/ubs-admin-sidebar.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2780 bugfix/prod fix header page
  src/app/shared/header/header.component.html
  src/app/store/reducers/employee.reducer.ts
Labels: bug

#2755 Change request/#4231/Validation event title date and time fields
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.html
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.scss
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/main/component/shared/components/input-error/input-error.component.ts
  src/assets/i18n/en.json
Labels: Event

#2767 Bugfix/#6469#6658/Fixing reflection of the image on a preview page
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
Labels: bug, Event

#2785 Bugfix/#6662#6517#6677#6518#6452#6167#3373#6692/All previous settings are not saved after selecting "back to editing" in the event preview window
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.spec.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.html
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.scss
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.spec.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.scss
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/events/components/event-details/event-schedule/event-schedule.component.html
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/components/events-preview-page/events-preview-page.component.html
  src/app/main/component/events/components/events-preview-page/events-preview-page.component.scss
  src/app/main/component/events/components/events-preview-page/events-preview-page.component.spec.ts
  src/app/main/component/events/components/events-preview-page/events-preview-page.component.ts
  src/app/main/component/events/components/images-container/images-container.component.scss
  src/app/main/component/events/components/images-container/images-container.component.ts
  src/app/main/component/events/events-routing.module.ts
  src/app/main/component/events/events.module.ts
  src/app/main/component/events/models/events.interface.ts
  src/app/main/component/events/services/events.service.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/component/shared/components/input-error/input-error.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/service/localstorage/local-storage.service.spec.ts
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, Event

#2792 Bugfix/#6657/Incorrect error message in description, when user create habit
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.scss
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.html
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/all-habits/components/habits-list-view/habits-list-view.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/component/user/components/shared/components/habits-gallery-view/habits-gallery-view.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, Habits

#2807 bugfix/#6227-Chahge-styles-of-pop-up-window-Filters-of-the-order-page
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/styles.scss
Labels: bug, UI

#2789 bugfix/#6414 Edited data is not automatically displayed in the table after changes
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
Labels: bug, UI

#2810 bugfix/#6718-Eror-message-notification-appears-when-the-User-logs-out
  src/app/shared/header/header.component.ts
  src/app/store/actions/employee.actions.ts
  src/app/store/effects/employee.effects.ts
  src/app/store/reducers/employee.reducer.ts
  src/app/ubs/ubs-admin/components/ubs-admin-sidebar/ubs-admin-sidebar.component.ts
Labels: bug, UI

#2806 Bugfix/#5537/Added tabulation for profile avatar in profile page
  src/app/main/component/user/components/shared/components/user-profile-image/user-profile-image.component.html
Labels: bug, Profile
