Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-10, with the labels that each got.

#2687 Bugfix/#6350/Fixed bug with a default event image
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/images-container/images-container.component.ts
  src/assets/img/events/default-image.png
Labels: bug, Event

#2704 bugfix/#6369,6461-add-ability-go-to-second-step
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug, UI

#2702 Bugfix/#6162/The alert window after clicked "Delete" not matches the mockup for past Event
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/profile/users-achievements/users-achievements.component.spec.ts
  src/app/main/component/user/components/profile/users-achievements/users-achievements.component.ts
Labels: bug, Event, My Habits

#2710 bugfix/#6408 Add enable of the certificate field for order with unpaid payment status
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs/order-status.enum.ts
Labels: bug, UI

#2711 bugfix/#6489 Add snackbars for the tariffs page
  src/app/main/component/errors/mat-snack-bar/mat-snack-bar.component.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-station-pop-up/ubs-admin-tariffs-station-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-station-pop-up/ubs-admin-tariffs-station-pop-up.component.ts
Labels: bug, UI

#2712 Bugfix/#5788 Tooltips at tariffs filtets fields fully displayed
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.scss
Labels: bug, UI

#2713 bugfix/Change-payment-approach-from-order-list-at-the-user-page
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.ts
Labels: bug, UI

#2714 Bugfix/Change employee table page styles
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
Labels: bug, UI, javascript

#2705 feature-bugfix/#6372#6511/Added put request for edit habit functionality
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.html
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.scss
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.spec.ts
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/mocks/habit-assigned-mock.ts
  src/app/main/component/user/components/habit/mocks/shopping-list-mock.ts
  src/app/main/component/user/components/habit/models/interfaces/custom-habit.interface.ts
  src/app/main/component/user/components/profile/shopping-list/shopping-list.component.spec.ts
  src/app/main/component/user/components/profile/shopping-list/shopping-list.component.ts
  src/app/main/component/user/models/shoppinglist.interface.ts
  src/app/main/service/habit/habit.service.ts
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/store/actions/habit.actions.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/reducers/habit.reducer.ts
  src/app/store/state/app.state.ts
  src/app/store/state/habit.state.ts
Labels: Feature, Habits, My Habits

#2722 Bugfix/#6547/An image disappears on the edit page when user tries to edit a habit. There are lots of errors in the console.log
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-edit-shopping-list/habit-edit-shopping-list.component.ts
  src/app/main/component/user/components/habit/add-new-habit/habit-progress/habit-progress.component.ts
Labels: bug, Sev: minor, Habits

#2728 bugfix/#6531-User-can-not-pay-saved-order-from-orders-list
  src/app/main/service/localstorage/local-storage.service.ts
  src/app/ubs/ubs-user/ubs-user-orders/ubs-user-orders.component.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.spec.ts
  src/app/ubs/ubs/components/ubs-main-page/ubs-main-page.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.spec.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
Labels: bug, UI

#2729 Bugfix/#6468#6463#6535/User is not able to change the location of event after creation of this event. Some locations of the events contain null-s
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.spec.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/main/component/events/components/event-details/event-details.component.html
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/images-container/images-container.component.spec.ts
  src/app/main/component/events/components/images-container/images-container.component.ts
  src/app/main/component/events/models/events.interface.ts
  src/app/main/component/events/services/events.service.spec.ts
  src/app/main/component/events/services/events.service.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/service/localstorage/local-storage.service.spec.ts
Labels: bug, Sev: minor, UI, Event

#2739 bugfix/#6588 User can't pay order for location 20 km Kyiv Oblast
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2756 Bugfix/prod employee update
  src/app/shared/shared.module.ts
  src/app/shared/upload-photo-container/upload-photo-container.component.html
  src/app/shared/upload-photo-container/upload-photo-container.component.scss
  src/app/shared/upload-photo-container/upload-photo-container.component.spec.ts
  src/app/shared/upload-photo-container/upload-photo-container.component.ts
  src/app/store/actions/employee.actions.ts
  src/app/store/effects/employee.effects.ts
  src/app/store/reducers/employee.reducer.ts
  src/app/store/selectors/employee.ts
  src/app/store/state/employee.state.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/employee-models.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.spec.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.ts
Labels: bug, UI
