Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-06, with the labels that each got.

#2464 bugfix/Fix-open-Deactivate-and-Restore-pop-ups
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
Labels: bug, UI

#2476 fixed #5866
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-export-details/ubs-admin-export-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-time/table-cell-time.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/table-cell-time/table-cell-time.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: bug

#2480 change log and add style for edit button
  src/app/main/component/user/components/profile/edit-profile/social-networks/social-networks.component.ts
  src/app/main/component/user/components/profile/profile-widget/profile-header/profile-header.component.html
  src/app/main/component/user/components/profile/profile-widget/profile-header/profile-header.component.scss
  src/app/main/component/user/components/profile/profile-widget/profile-header/profile-header.component.spec.ts
  src/app/main/component/user/components/profile/profile-widget/profile-header/profile-header.component.ts
Labels: bug

#2482 bugfix/#5316,#5872,#5861,#5864,#5878,#5747-Fix-bugs-with-events
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.spec.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/i18n/Language.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: UI

#2491 bugfix/Change-employee-page-add-state-field-to-filter-zone
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/employee-models.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2500 bugfix/#5901,#4884,#5925-Fix-events-bugs
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate-add-certificate-pop-up/ubs-admin-certificate-add-certificate-pop-up.component.scss
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/assets/i18n/ua.json
Labels: UI

#2507 hotfix/fix-bug-of-calculating-the-amount-of-bonuses-when-using-a-certificate-in-the-order
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
Labels: bug

#2508 hotfix/prod-fix-bug-of-calculating-the-amount-of-bonuses
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
Labels: bug

#2518 bugfix/#5412,#5803-Add-fix-order-table-bugs
  src/app/shared/dialog-pop-up/dialog-pop-up.component.html
  src/app/shared/dialog-pop-up/dialog-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.scss
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2540 Bugfix/#5965#5964#5963#5962#5961/create new
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news-form-builder.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.scss
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.html
  src/app/main/component/eco-news/components/eco-news-detail/eco-news-detail.component.scss
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.spec.ts
  src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
  src/app/shared/ubs-base-sidebar/ubs-base-sidebar.component.scss
  src/app/store/actions/ecoNews.actions.ts
  src/app/store/effects/ecoNews.effects.ts
  src/app/store/reducers/ecoNews.reducer.ts
  src/app/ubs/ubs-user/ubs-user-messages/ubs-user-messages.component.scss
Labels: bug
