Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-01, with the labels that each got.

#2037 TestFIx
  src/app/ubs/ubs-admin/components/shared/components/time-picker/time-picker.component.spec.ts
Labels: bug, UI

#1985 #4657: update list of order statuses
  src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
Labels: bug, UI

#2033 disabled addresses for appropriate tariff
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.spec.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
Labels: bug, UI

#2034 Rename "Shopping List" to "To-do list"
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: GreenCity

#2039 bugfix/#4826 - UBS Admin - Tariffs - change style of cursor and add click events
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
Labels: bug, UI

#2041 fixed ubs admin - add service - en description placeholder
  src/assets/i18n/ubs-admin/en.json
Labels: bug, UI

#2044 display certificate points
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
Labels: bug, UI

#2043 bugfix/#4567 - ubs order - style for mobile
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
Labels: bug, UI

#2050 Bugfix#4154 UI inconsistencies on the order page
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/ua.json
Labels: UI, GreenCity

#2045 changed patterns for name, surname and email
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2046 Bugfix/#4910 order status for declining payment
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.html
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.spec.ts
  src/app/ubs/ubs/components/ubs-confirm-page/ubs-confirm-page.component.ts
Labels: bug, UI

#2048 bugfix/#4875/_ENDPOINTS]_Refactor_Dto's_bodies_
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/ubs/ubs-admin/components/add-order-not-taken-out-reason/add-order-not-taken-out-reason.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
Labels: UI

#2051 #4912: changed condition for oversum
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
Labels: bug, UI

#2053 bugfix/#4930 - pricing page - Add Location - active cities en translate
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2059 Bugfix/Habits/Back-to-my-habits-button-is-missing
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.html
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.scss
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-new-habit/add-new-habit.component.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI, GreenCity

#2069 bugfix/#4864 pricing page - limits style
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.scss
Labels: bug, UI

#2061 Bugfix/#4940 pricing page add location pop up translation region ua to en
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2072 bugfix/#4973/User see incorrect error message when he/she enters forbidden Name in the Name field on 'Edit profile' page
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2052 Bugfix/#4903-count-limit-big-bags
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.html
  src/app/ubs/ubs/models/ubs.interface.ts
Labels: bug, UI

#2083 Bugfix/#5021 pricing page tariffs add edit courier translation
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-courier-pop-up/ubs-admin-tariffs-courier-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI

#2079 #5000/disable_textarea
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.html
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.scss
Labels: bug, UI

#2078 bugfix/#5002/The amount of packages isn't automatically received in the column "Вивезена кількість" from the column"Підтверджена кількість" when order status 'Виконано' of page "Order"
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug, UI

#2066 Bugfix/#4950 tariffs cards translation to en
  src/app/main/pipe/tariff-status-pipe/tariff-status.pipe.spec.ts
  src/app/main/pipe/tariff-status-pipe/tariff-status.pipe.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
Labels: bug, UI

#2076 bugfix/#4868 pricing page limits - inputs check number
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
Labels: bug, UI

#2067 bugfix/#4858/Pricing_page._Admin._Limits]_Previously_typed_limits_aren't_erased,_when_another_limit_option_is_chosen_
  src/app/ubs/ubs-admin/components/shared/limits-validator/limits.validator.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
Labels: bug, UI

#2093 fixed tariffs pop up test error
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2090 bugfix/#4956 - added missing special characters to city pattern
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2097 bugfix/#5082/[Order Details] non responsive pop-up for phones
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.scss
Labels: bug, UI

#2089 bugfix/#4949/getServiceRefactoring
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/create-edit-tariffs-service-form-builder.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, enhancement, technical, UI, GreenCity

#2091 Bugfix/#4955 edited profile name pattern and error message
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/assets/patterns/patterns.ts
Labels: bug, UI

#2099 Bugfix/#4819 tariffs location pop up region autofill
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts
Labels: bug, UI

#2102 Bugfix / Not working filter on the All Habit page
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
  src/app/main/component/eco-news/components/news-list/news-list.component.ts
  src/app/main/component/eco-news/components/news-preview-page/news-preview-page.component.ts
  src/app/main/component/eco-news/models/create-news-interface.ts
  src/app/main/component/eco-news/models/eco-news-model.ts
  src/app/main/component/eco-news/services/create-eco-news.service.ts
  src/app/main/component/eco-news/services/eco-news.service.ts
  src/app/main/component/shared/components/tag-filter/tag-filter.component.ts
  src/app/main/component/shared/components/tag-filter/tag-filter.model.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.spec.ts
  src/app/main/component/user/components/habit/all-habits/all-habits.component.ts
  src/app/main/service/habit/habit.service.spec.ts
  src/app/main/service/habit/habit.service.ts
  src/app/main/service/place/place.service.ts
Labels: bug, UI, GreenCity

#2112 Bugfix/#4996 reset inputs in order details blocks
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: bug, UI
