Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-04, with the labels that each got.

#2278 Bugfix/#5497 user cannot save comment at the address field on the order
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
Labels: UI

#2293 bugfix/#5563,#5548,#5541-Added some styles changes
  src/app/main/component/places/places.component.html
  src/app/main/component/places/places.component.spec.ts
  src/app/main/component/places/places.component.ts
  src/app/main/component/user/components/profile/edit-profile/social-networks/social-networks.component.scss
  src/app/shared/header/header.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: UI

#2295 Bugfix/#5585 ubs admin order table filtration by city and districts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/admin-table.service.spec.ts
  src/app/ubs/ubs-admin/services/admin-table.service.ts
Labels: bug, UI

#2297 bugfix/#5581,#5592,#5577-Fixed-some-styles
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
Labels: UI

#2291 Code optimization ubs global buttons
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up-ubs.component.scss
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.html
  src/app/main/component/shared/components/warning-pop-up/warning-pop-up.component.scss
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.html
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-cancel-pop-up/ubs-user-order-cancel-pop-up.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-order-cancel-pop-up/ubs-user-order-cancel-pop-up.component.scss
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.html
  src/app/ubs/ubs-user/ubs-user-orders-list/ubs-user-orders-list.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.scss
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.scss
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-location-popup/ubs-order-location-popup.component.spec.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
  src/typography/_colorsUbs.scss
  src/typography/_typography.scss
  src/typography/_typographyUbs.scss
Labels: UI

#2309 Bugfix/#5542/#5544 my space display calendar and habit card shadow
  src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.scss
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.html
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.scss
  src/app/main/component/user/components/profile/profile.component.scss
Labels: bug, UI

#2313 bugfix/prod#5383,#5384,#5316-Add-phone-validation-and-change-fields-name
  src/app/shared/ubs-input-error/ubs-input-error.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/assets/i18n/ubs-admin/en.json
Labels: UI

#2310 Bugfix/#5607 ubs user profile fix auto district name
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
Labels: bug, UI

#2318 Bugfix/#5614/#5633 create custom habit tags and description
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.scss
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
  src/app/main/component/shared/components/tags-select/tags-select.component.html
  src/app/main/component/shared/components/tags-select/tags-select.component.spec.ts
  src/app/main/component/shared/components/tags-select/tags-select.component.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.ts
  src/app/main/mocks/tags-list-mock.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
  src/styles.scss
Labels: bug, UI

#2299 feature/#5597/[Events]Add possibility to choose filters
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/models/event-consts.ts
Labels: bug, enhancement, UI, GreenCity

#2338 bugfix/removed color red tooltip of tags
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.html
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.spec.ts
  src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
  src/app/main/component/shared/components/tags-select/tags-select.component.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.html
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.spec.ts
  src/app/main/component/user/components/habit/add-edit-custom-habit/add-edit-custom-habit.component.ts
  src/app/main/component/user/components/profile/calendar/habits-popup/habits-popup.component.spec.ts
  src/app/main/component/user/components/profile/calendar/habits-popup/habits-popup.component.ts
  src/app/main/component/user/components/profile/users-friends/users-friends.component.html
  src/app/main/component/user/components/profile/users-friends/users-friends.component.scss
  src/app/main/interface/habit/custom-habit.interface.ts
  src/app/main/service/habit/habit.service.ts
Labels: bug, UI

#2351 Bugfix/change styles of employee page according to new mock-up
  src/app/shared/ubs-input-error/ubs-input-error.component.html
  src/app/shared/ubs-input-error/ubs-input-error.component.scss
  src/app/shared/ubs-input-error/ubs-input-error.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/img/ubs-admin-employees/arrow-down.svg
  src/assets/img/ubs-admin-employees/arrow-up.svg
  src/assets/img/ubs-admin-employees/cross.svg
Labels: UI

#2357 bugfix/prod-Changed-employee-page
  src/app/main/component/user/models/error-type.model.ts
  src/app/shared/ubs-input-error/ubs-input-error.component.html
  src/app/shared/ubs-input-error/ubs-input-error.component.scss
  src/app/shared/ubs-input-error/ubs-input-error.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2350 Tech task/add place id on add address
  src/app/main/service/location/location.service.ts
  src/app/main/service/location/location.spec.ts
  src/app/shared/to-first-capital-letter/to-first-capital-letter.service.spec.ts
  src/app/shared/to-first-capital-letter/to-first-capital-letter.service.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.html
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.spec.ts
  src/app/shared/ubs-add-address-pop-up/ubs-add-address-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-address-details/ubs-admin-address-details.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-user/services/client-profile.service.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
Labels: UI

#2285 Bugfix/#5535,#5564,#5565,#5566,#5567,#5572,#5573,#5578,#5583,#5584,#5590,#5604 -Add-validation-to-service-popup-fields
  src/app/main/component/shared/components/input-error/input-error.component.ts
  src/app/main/component/user/models/error-type.model.ts
  src/app/shared/ubs-input-error/ubs-input-error.component.ts
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
  src/assets/patterns/patterns.ts
Labels: UI

#2361 bugfix/#5688/Events]Incorrect_location_list_
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/models/event-consts.ts
  src/app/main/component/events/models/events.interface.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/service/localstorage/local-storage.service.spec.ts
Labels: bug, enhancement, UI, GreenCity
