Repository ita-social-projects/GreenCityClient, pull requests merged in 2023-05, with the labels that each got.

#2366 Bugfix/Add-tests-to-ubs-admin-employee-component
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/employee-models.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
Labels: UI

#2376 bugfix/#5715, #5693-Fix-display-order-status-and-payment-status-for-canceled-order
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
Labels: UI

#2386 bugfix/prod-Tasks#5641,#5649,#5693,#5598,#5599,#5705,#5717,#5718,#5715,#5693
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-history/ubs-admin-order-history.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/services/table-height.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/assets/i18n/ubs/ua.json
Labels: UI

#2383 bugfix/#5641,#5649,#5693,#5598,#5599,#5705,#5717,#5718-Some-UI-fixes
  src/app/main/component/events/components/events-list/events-list.component.scss
  src/app/main/component/shared/components/events-list-item/events-list-item.component.html
  src/app/main/component/shared/components/events-list-item/events-list-item.component.scss
  src/app/ubs/ubs-admin/components/add-order-cancellation-reason/add-order-cancellation-reason.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/assets/i18n/ubs/ua.json
Labels: bug, UI

#2397 bugfix/#5726,#5727,5731,#5739,#5740,#5741,#5742,#5748,#5749-Fixes-on-Tariffs-page
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.html
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.ts
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/modal-text/modal-text.component.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.scss
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.scss
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: bug, UI

#2412 bugfix/#5725 - All habits - mobile screen style fix
  src/app/main/component/user/components/habit/all-habits/all-habits.component.scss
Labels: bug, UI

#2413 Bugfix/#5752,#5753,#5754,#5755,#5757,#5758,#5744, #5661-Fix event creation bugs
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.html
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.scss
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.spec.ts
  src/app/main/component/events/components/create-edit-events/create-edit-events.component.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.html
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.spec.ts
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
  src/app/main/component/events/components/event-details/event-details.component.spec.ts
  src/app/main/component/events/components/event-details/event-details.component.ts
  src/app/main/component/events/components/events-list/events-list.component.html
  src/app/main/component/events/components/events-list/events-list.component.spec.ts
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/events/models/event-consts.ts
  src/app/main/component/events/models/events.interface.ts
  src/app/main/component/events/services/events.service.ts
  src/app/main/component/shared/components/events-list-item/events-list-item.component.spec.ts
  src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.spec.ts
  src/app/main/component/user/components/profile/users-friends/friend-dashboard/friend-dashboard.component.html
  src/app/main/service/localstorage/local-storage.service.spec.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI, GreenCity

#2414 bugfix/#4853/#5782 - All Habits - view button style and added translation for "items found"
  src/app/main/component/user/components/habit/all-habits/all-habits.component.html
  src/app/main/component/user/components/habit/all-habits/all-habits.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, UI

#2417 Bugfix/prod/#5770,#5778,#5598 fixes employee page and change error msg at the sign-in page
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.html
  src/app/main/component/auth/components/confirm-restore-password/confirm-restore-password.component.ts
  src/app/main/component/auth/components/error/error.component.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.html
  src/app/main/component/auth/components/sign-in/sign-in.component.ts
  src/app/main/component/auth/components/sign-up/sign-up.component.html
  src/app/main/component/auth/components/sign-up/sign-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
Labels: bug, UI

#2422 bugfix/#5734-Change-deactivate-pop-up-according-to-mock-up
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-tariffs.enum.ts
Labels: bug

#2429 bugfix/#5784,#5788,#5816,#5817-Some-fix-tariff-page-bugs
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-tariff-service-pop-up/ubs-admin-tariffs-add-tariff-service-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-pricing-page.component.scss
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2434 bugfix/prod-#5734-Change-deactivate-pop-up-according-to-mock-up
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-tariffs.enum.ts
  src/app/ubs/ubs-admin/services/tariffs.service.spec.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
Labels: UI

#2451 bugfix/prod#5463-remove-resize-descr
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.scss
Labels: UI

#2455 Bugfix/prod#5726,#5843,#5844,#5845,#5847,#5848 add fixes of deactivated and activated tariffs pop ups
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.html
  src/app/ubs/ubs-admin/components/shared/components/dialog-tariff/dialog-tariff.component.ts
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.html
  src/app/ubs/ubs-admin/components/shared/components/tariff-deactivate-confirmation-pop-up/tariff-deactivate-confirmation-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/tariff-status.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
  src/app/ubs/ubs-admin/services/tariffs.service.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
Labels: UI

#2431 bugfix/#5470/UBS_Admin.Orders.OrdersDetails
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-status/ubs-admin-order-status.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order/ubs-admin-order.component.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
Labels: bug

#2445 bugfix/#5815,#5794-Fix-infinity-scroll-in-the-event-page
  src/app/main/component/events/components/events-list/events-list.component.ts
  src/app/main/component/shared/components/events-list-item/events-list-item-modal/events-list-item-modal.component.scss
Labels: UI

#2446 bugfix/#5812-Add-validation-fields-in-the-add-employee-popup
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
Labels: UI

#2449 bugfix/#5024/EditProfile/social_networks
  src/app/main/component/user/components/profile/edit-profile/social-networks/social-networks.component.spec.ts
  src/app/main/component/user/components/profile/edit-profile/social-networks/social-networks.component.ts
  src/app/main/component/user/components/profile/profile-service/profile.service.ts
Labels: bug

#2454 bugfix/#5726,#5843,#5844,#5845,#5847,#5848-Add-fixes-of-deactivated-and-activated-tariffs-pop-ups
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/tariff-status.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-card-pop-up/ubs-admin-tariffs-card-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-deactivate-pop-up/ubs-admin-tariffs-deactivate-pop-up.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
  src/app/ubs/ubs-admin/models/tariffs.interface.ts
Labels: UI

#2458 bugfix/Employees-page-emplementation-employee-authorities
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/employee-models.enum.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/app/ubs/ubs-admin/services/ubs-admin-employee.service.ts
  src/app/ubs/ubs-admin/ubs-admin.module.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: UI

#2443 add changes, can edit event with user info, refactore code
  src/app/main/component/events/components/event-date-time-picker/event-date-time-picker.component.ts
Labels: bug

#2462 #5812-Add-validation-fields-in-the-add-employee-popup
  src/app/ubs/ubs-admin/components/add-violations/add-violations.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
Labels: UI
