Repository ita-social-projects/GreenCityClient, pull requests merged in 2024-01, with the labels that each got.

#2856 bugfix/#6789-button-Next-at-first-step-page-not-disable-when-is-error-msg
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
Labels: bug, UI

#2864 Bugfix/fix change bags quantity
  src/app/main/component/shared/components/form-base/form-base.component.ts
  src/app/store/actions/order.actions.ts
  src/app/store/reducers/order.reducer.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.ts
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.html
  src/app/ubs/ubs/components/ubs-personal-information/ubs-personal-information.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
  src/app/ubs/ubs/services/order.service.ts
Labels: bug

#2866 Feature/search by events on header search pop-up
  src/app/main/model/search/eventsSearch.model.ts
  src/app/main/model/search/newsSearch.model.ts
  src/app/main/model/search/search.model.ts
  src/app/main/model/search/tipsSearch.model.ts
  src/app/main/service/search/search.service.ts
  src/app/shared/search-all-results/search-all-results.component.html
  src/app/shared/search-all-results/search-all-results.component.spec.ts
  src/app/shared/search-all-results/search-all-results.component.ts
  src/app/shared/search-item/search-item.component.html
  src/app/shared/search-item/search-item.component.spec.ts
  src/app/shared/search-item/search-item.component.ts
  src/app/shared/search-popup/search-consts.ts
  src/app/shared/search-popup/search-popup.component.html
  src/app/shared/search-popup/search-popup.component.scss
  src/app/shared/search-popup/search-popup.component.spec.ts
  src/app/shared/search-popup/search-popup.component.ts
  src/app/store/actions/ecoEvents.actions.ts
  src/app/store/effects/ecoEvents.effects.ts
  src/app/store/reducers/ecoEvents.reducer.ts
  src/assets/i18n/en.json
  src/assets/i18n/ua.json
Labels: bug, Feature

#2888 bugfix/fix-payment-section-order-at-admin-side
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.html
  src/app/ubs/ubs-admin/components/add-payment/add-payment.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug, UI
