Repository ita-social-projects/GreenCityClient, pull requests merged in 2025-09, with the labels that each got.

#3855 Chore/Addition to env files
  README.md
  azure-pipelines-prod.yml
  scripts/setenv.ts
Labels: Feature

#3842 Chore/3841 Remove CAPTCHA
  src/app/main/component/auth/auth.module.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.html
  src/app/main/component/auth/components/sign-in/sign-in.component.spec.ts
  src/app/main/component/auth/components/sign-in/sign-in.component.ts
  src/app/main/component/auth/components/turnstile-captcha/turnstile-captcha.component.html
  src/app/main/component/auth/components/turnstile-captcha/turnstile-captcha.component.scss
  src/app/main/component/auth/components/turnstile-captcha/turnstile-captcha.component.spec.ts
  src/app/main/component/auth/components/turnstile-captcha/turnstile-captcha.component.ts
  src/app/store/effects/auth.effects.ts
  src/assets/i18n/en.json
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/uk.json
  src/assets/i18n/uk.json
Labels: refactoring

#3838 Chore/3837 Remove dropdown with payment methods
  src/app/ubs/ubs/components/ubs-order-form/ubs-order-form.component.ts
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.html
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.scss
  src/app/ubs/ubs/components/ubs-submit-order/ubs-submit-order.component.ts
  src/app/ubs/ubs/models/ubs.interface.ts
  src/assets/i18n/ubs/en.json
  src/assets/i18n/ubs/uk.json
Labels: refactoring

#3830 bugfix/fixed search field
  package-lock.json
  package.json
  src/app/chat/component/client-info-panel/client-info-panel.component.html
  src/app/chat/component/client-info-panel/client-info-panel.component.scss
  src/app/chat/component/client-info-panel/client-info-panel.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3861 HOTFIX/ error in json files
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3884 Spelina/float digits and certificate pop-up fix
  src/app/ubs/ubs-user/components/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.html
  src/app/ubs/ubs-user/components/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.spec.ts
  src/app/ubs/ubs-user/components/ubs-user-orders-list/ubs-user-order-payment-pop-up/ubs-user-order-payment-pop-up.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3883 Bugfix/9092-amount-of-bonuses-displays-with-2-digits-after-point
  src/app/ubs/ubs-user/components/ubs-user-order-details/ubs-user-order-details.component.html
  src/app/ubs/ubs-user/components/ubs-user-order-details/ubs-user-order-details.component.spec.ts
  src/app/ubs/ubs-user/components/ubs-user-order-details/ubs-user-order-details.component.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.html
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-details.component.html
Labels: bug
