Repository ita-social-projects/GreenCityClient, pull requests merged in 2025-08, with the labels that each got.

#3768 Refactored the components
  src/app/chat/component/chat-page/chat-page.component.spec.ts
  src/app/chat/component/chat-page/chat-page.component.ts
  src/app/chat/component/client-info-panel/client-info-panel.component.html
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: bug

#3770 Bugfix/#8739 The customers filter did not work
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.ts
Labels: bug

#3761 Bugfix/#8493 Buttons yes and no were merged
  src/app/ubs/ubs-user/components/ubs-user-orders-list/ubs-user-order-cancel-pop-up/ubs-user-order-cancel-pop-up.component.scss
  src/app/ubs/ubs/services/order.service.spec.ts
Labels: bug

#3760 Bugfix/#7660 to do list could not be updated
  src/app/greencity/modules/user/components/habit/add-new-habit/add-new-habit.component.ts
Labels: bug

#3771 Feature/3769/the images in the chat are not displayed
  src/app/chat/component/chat-page/chat-page.component.html
  src/app/chat/component/chat-page/chat-page.component.scss
  src/app/chat/component/chat-page/chat-page.component.spec.ts
  src/app/chat/component/chat-page/chat-page.component.ts
  src/app/chat/component/image-modal/image-modal.component.html
  src/app/chat/component/image-modal/image-modal.component.scss
  src/app/chat/component/image-modal/image-modal.component.spec.ts
  src/app/chat/component/image-modal/image-modal.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/ua.json
Labels: enhancement, refactoring, UI, Feature

#3776 Bugfix/8708 Date picker date input had incorrect type
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.ts
Labels: bug

#3778 Bugfix/8579 8580 Display of "enroll money to account" worked incorrectrly
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-order-payment/ubs-admin-order-payment.component.ts
  src/app/ubs/ubs/services/order.service.spec.ts
Labels: bug

#3779 Bugfix/8454 Character from another language caused inconsistency in the UI
  src/app/ubs/ubs/services/order.service.spec.ts
  src/assets/i18n/ua.json
Labels: bug

#3782 placeholder-text-fixed
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.scss
Labels: bug

#3785 Bugfix/3784 add user names instead of nicknames
  src/app/chat/component/chat-page/chat-page.component.html
  src/app/chat/component/chat-page/chat-page.component.spec.ts
  src/app/chat/component/chat-page/chat-page.component.ts
Labels: bug

#3786 Bugfix/8900 Notifications cron issue
  src/app/ubs/shared/pipes/cron-pipe/cron.pipe.spec.ts
  src/app/ubs/shared/pipes/cron-pipe/cron.pipe.ts
  src/app/ubs/ubs-admin/services/cron/cron.service.ts
  src/app/ubs/ubs-admin/services/cron/locales/en.json
  src/app/ubs/ubs-admin/services/cron/locales/uk.json
Labels: bug

#3787 Bugfix/8960 incorrect chat button shown on customer details
  src/app/chat/component/chat-page/chat-page.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customer-details/ubs-admin-customer-details.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customer-details/ubs-admin-customer-details.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customer-details/ubs-admin-customer-details.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customer-details/ubs-admin-customer-details.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.scss
Labels: bug

#3783 bugfix/8956 selecting all option hides other options and prevents reselection and unselected value still displayed in the input field
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.ts
Labels: bug

#3766 Bugfix/8756 the search does not work on customers page
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-customers/ubs-admin-customers.component.ts
Labels: bug

#3831 feature/renewed skipped tests
  src/app/ubs/ubs-admin/components/ubs-admin-certificate/ubs-admin-certificate.component.spec.ts
Labels: Feature

#3828 Bugfix/8986 8987 8846 authorities issues
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/store/actions/authority.actions.ts
  src/app/store/effects/authority.effects.spec.ts
  src/app/store/effects/authority.effects.ts
  src/app/store/effects/employee.effects.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/reducers/authority.reducer.spec.ts
  src/app/store/reducers/authority.reducer.ts
  src/app/store/selectors/authority.selectors.spec.ts
  src/app/store/selectors/authority.selectors.ts
  src/app/store/state/app.state.ts
  src/app/store/state/authority.state.ts
  src/app/ubs/shared/components/address-input/address-input.component.spec.ts
  src/app/ubs/shared/components/show-imgs-pop-up/show-imgs-pop-up.component.html
  src/app/ubs/shared/components/upload-photo-container/upload-photo-container.component.spec.ts
  src/app/ubs/shared/components/upload-photo-container/upload-photo-container.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-edit-form/ubs-admin-employee-edit-form.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-permissions-form/ubs-admin-employee-permissions-form.component.ts
  src/app/ubs/ubs-admin/models/employee-permissions.model.ts
  src/app/ubs/ubs-admin/models/ubs-admin.interface.ts
  src/app/ubs/ubs-admin/services/authority.service.spec.ts
  src/app/ubs/ubs-admin/services/authority.service.ts
Labels: bug

#3825 Bugfix/8854 Search employee
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee-table/ubs-admin-employee-table.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-employee/ubs-admin-employee.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3813 Bugfix/7240 8962 8978 notifications issues
  src/app/ubs/ubs-admin/components/ubs-admin-notification-list/ubs-admin-notification-list.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification-settings/ubs-admin-notification-settings.component.html
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification-settings/ubs-admin-notification-settings.component.scss
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification-settings/ubs-admin-notification-settings.component.ts
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification.component.spec.ts
  src/app/ubs/ubs-admin/components/ubs-admin-notification/ubs-admin-notification.component.ts
  src/app/ubs/ubs-admin/models/notifications.model.ts
  src/app/ubs/ubs-admin/services/cron/cron.service.spec.ts
  src/app/ubs/ubs-admin/services/notifications.mock.ts
  src/app/ubs/ubs-admin/services/notifications.service.spec.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3832 Bugfix/8990 unable to set previous district for kyiv address
  src/app/ubs/ubs-user/components/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/components/ubs-user-profile-page/ubs-user-profile-page.component.ts
Labels: bug

#3824 telegram-subscription-fix
  src/app/ubs/ubs-user/components/ubs-user-profile-page/ubs-user-profile-page.component.html
  src/app/ubs/ubs-user/components/ubs-user-profile-page/ubs-user-profile-page.component.spec.ts
  src/app/ubs/ubs-user/components/ubs-user-profile-page/ubs-user-profile-page.component.ts
  src/assets/i18n/ubs-admin/en.json
  src/assets/i18n/ubs-admin/uk.json
Labels: bug

#3818 bugfix/8347 certificates could not be activated
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.spec.ts
  src/app/ubs/ubs/components/ubs-order-details/ubs-order-certificate/ubs-order-certificate.component.ts
Labels: bug
